### ISSUE TITLE
Complete German translation

### ISSUE THREAD

**Issue by matjack1** [datocms/translations#12]
We are looking for help to finish translating the CMS in German.

If you are interested please get in touch via https://www.datocms.com/support/ so that I can invite you on [Loco](https://localise.biz/) and give you more details.

~€100 of credits available!

**Comment by fabianunger** [comment]
I would be in for that! Contacted you guys via the support just now. Also my last pull request got kind of lost along the way to Loco. I would love to complete that!

**Comment by Crease29** [comment]
If you need any help with that, let me know.

**Comment by stefanoverna** [comment]
@Crease29 invited inside our translation system!

**Comment by matjack1** [comment]
hey @Crease29 thank you, did you complete the translations yesterday? There are just a couple more flagged as fuzzy, meaning that the English string has been changed meanwhile.

If you could do that I'll assign you the credit and close this. Thank you!

@fabianunger you'll get some credit as well for having done the previous part!

Please get in touch both over at https://www.datocms.com/support/ with the DatoCMS email account, so that I can know exactly to who I need to assign the credit.

Thank you very much!!! :)

**Comment by Crease29** [comment]
Hi @matjack1, 

I've done like 250 translations yesterday and there are still some open. There are also some comments from me. Please check them 🙂 I'll translate the untranslated ones and will check the fuzzy ones afterwards.

I've sent a message through your contact form. Thanks!

**Comment by fabianunger** [comment]
🎉 Yeah we made it   🎉 Thanks @Crease29 for your help!

**Comment by matjack1** [comment]
Thank you very much both!! You are incredible :)

I'll be in touch for the credit via email later today or tomorrow.
