### ISSUE TITLE
Complete French translation

### ISSUE THREAD

**Issue by matjack1** [datocms/translations#13]
We are looking for help to finish translating the CMS in French.

If you are interested please get in touch via https://www.datocms.com/support/ so that I can invite you on [Loco](https://localise.biz/) and give you more details.

~€100 of credits available!

**Comment by imhaage** [comment]
Hi! I just tried DatoCMS and I think it's really a great tool. I discovered that some translations are missing. I'm a french developer and I would be happy to help you with the french translation if you still need help.
