### ISSUE TITLE
Complete Czech translation

### ISSUE THREAD

**Issue by matjack1** [datocms/translations#14]
We are looking for help to finish translating the CMS in Czech.

If you are interested please get in touch via https://www.datocms.com/support/ so that I can invite you on [Loco](https://localise.biz/) and give you more details.

~€120 of credits available!

**Comment by vonschau** [comment]
Hi @matjack1,

Czech translation completed.

**Comment by vonschau** [comment]
Though, some strings are still not in Loco, ie.:
- sections' captions in Admin area .... PROJECT, STRUCTURE, WEBHOOKS, DEPLOYMENT
- system fields in filters (Updated At, Created At, ....)
- "Settings" in Content area menu

**Comment by matjack1** [comment]
Thank you very much @vonschau for pointing that out!

I've added the strings for translation. And please confirm that you've received your credit.

Thank you!!
