### ISSUE TITLE
Complete Spanish translation

### ISSUE THREAD

**Issue by matjack1** [datocms/translations#16]
We are looking for help to finish translating the CMS in Spanish.

If you are interested please get in touch via https://www.datocms.com/support/ so that I can invite you on [Loco](https://localise.biz/) and give you more details.

~€200 of credits available!

**Comment by Chompas** [comment]
I'll help with that 👍

**Comment by guidogr95** [comment]
I would like to contribute to this

**Comment by matjack1** [comment]
sure @guidogr95 please send over https://www.datocms.com/support/ your email address so that I can add you to our https://localise.biz/ account. And maybe register there too before.

Thank you very much for doing this :)

**Comment by matjack1** [comment]
This is all done now, if I've not contacted you for credit please be in touch specifying how many records did you translate. Thank you!!

**Comment by guidogr95** [comment]
Hi, I was wondering when we're gonna be able to see this translation in action on the CMS. Thanks

**Comment by stefanoverna** [comment]
Hey @guidogr95! Thanks for asking, there was actually a little bug that prevented the Spanish translations to work!

Just go to Language settings and it should work now!

<img width="257" alt="Schermata 2020-02-27 alle 09 19 37" src="https://user-images.githubusercontent.com/51573/75425084-49420b00-5942-11ea-9b13-06676fb8dd28.png">
