### ISSUE TITLE
Better german translation

### ISSUE THREAD

**Issue by sbatial** [datocms/translations#20]
Some words doesn't make sense or are a bit unusual in that place.

**Comment by sbatial** [comment]
I would take and fix those. Just wanted to have it officialy opened.

**Comment by matjack1** [comment]
Thank you for offering to help!

Please send at support@datocms.com your email address so that I can add you to Loco so that you can provide your improvements.

Thanks a lot!

**Comment by sbatial** [comment]
@matjack1 
Oh sorry.
Totally forgot that.
I began w/ some of the open translations in Loco now.

**Comment by matjack1** [comment]
No worries @BodeSpezial I've closed the issue as the translation is done! If you want to modify or update more translations feel free to do it anyway!

Be in touch if you need any help though.
