### ISSUE TITLE
How to keep translations in sync

### ISSUE THREAD

**Issue by matjack1** [datocms/translations#7]
Hello,

we are looking for ways to manage our translations and to keep them updated.

Do you have any suggestions for this? Thank you!

**Comment by TotomInc** [comment]
I really recommend [Crowdin](https://crowdin.com) which helps users and developers to keep in sync with translations. They have third-party tools integration like with [GitHub](https://support.crowdin.com/github-integration/).

**Comment by matjack1** [comment]
thank you so much @TotomInc !

We are trying now https://localise.biz which seems good enough for us and has a pricing model that is much cheaper for us. We still need to make a few tests and make it official though :)

**Comment by TotomInc** [comment]
Alright, let us know when everything is done!

**Comment by matjack1** [comment]
All setup and ready!
